services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=xmldatabase'
      - 'POSTGRES_PASSWORD=secretxml'
      - 'POSTGRES_USER=userxml'
    ports:
      - '5435:5432'
