version: '3.8'

services:
  app:
    build: .
    container_name: cv24v2-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - xml-network

  db:
    image: 'postgres:latest'
    container_name: cv24v2-db
    environment:
      - 'POSTGRES_DB=xmldatabase'
      - 'POSTGRES_PASSWORD=secretxml'
      - 'POSTGRES_USER=userxml'
    ports:
      - "5435:5432"
    networks:
      - xml-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_cv24
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - xml-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_cv24
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - xml-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=cv24Secret

networks:
  xml-network: